version: 2

jobs:
  rustfmt:
    docker:
      - image: "cimg/rust:1.57"
    steps:
      - checkout
      - run:
          name: install rustfmt
          command: rustup component add rustfmt
      - run:
          name: run rustfmt
          command: >
            for day in day*; do
              cd "$day"
              echo "Checking $day"
              cargo fmt -- --check
              cd ..
            done

  clippy:
    docker:
      - image: "cimg/rust:1.57"
    steps:
      - checkout
      - run:
          name: install clippy
          command: rustup component add clippy
      - run:
          name: display clippy version
          command: cargo clippy -- --version
      - run:
          name: run clippy
          command: >
            for day in day*; do
              cd "$day"
              echo "Checking $day"
              cargo clippy -- -Dwarnings
              cd ..
            done

  test:
    docker:
      - image: "cimg/rust:1.57"
    steps:
      - checkout
      - run:
          name: run tests
          command: >
            for day in day*; do
              cd "$day"
              echo "Testing $day"
              cargo test
              cd ..
            done

workflows:
  version: 2
  test_solutions:
    jobs:
      - rustfmt
      - clippy
      - test
